# Generated by Django 4.0.2 on 2022-12-22 14:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_room_receipts_money_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='users',
            field=models.ManyToManyField(related_name='user_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
