# Generated by Django 4.0.2 on 2022-12-23 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_room_creator'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='receipts',
            new_name='receipt',
        ),
    ]
