# Generated by Django 4.0.2 on 2022-12-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_receipts_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='money_request',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
