# Generated by Django 4.0.2 on 2022-12-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_money_request_description_receipt_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='money_request',
            name='key',
            field=models.CharField(default='', max_length=20),
        ),
    ]
