# Generated by Django 4.0.2 on 2022-12-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_money_request_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='money_request',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
