# Generated by Django 4.0.2 on 2022-12-26 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_money_request_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='description',
        ),
    ]
