# Generated by Django 4.0.2 on 2022-12-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_receipt_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='money_request',
            name='status',
        ),
        migrations.AddField(
            model_name='money_request',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
